server:
  port: 6060

spring:
  application:
    name: structure-health-backend
  datasource:
    url: ${STRUCTURE_HEALTH_DB_URL:jdbc:postgresql://localhost:5432/strutured_care}
    username: ${STRUCTURE_HEALTH_DB_USERNAME:strutured_care}
    password: ${STRUCTURE_HEALTH_DB_PASSWORD:strutured_care}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info

structure-health:
  frontend:
    allowed-origins: ${STRUCTURE_HEALTH_FRONTEND_ALLOWED_ORIGINS:http://localhost:6070,http://localhost:6060}
